/**
 * AUTO-GENERATED by scripts/upload-videos-blob.ts. Do not edit by hand —
 * rerun the uploader to refresh. Maps a lesson word to its Veo 3.1 clip
 * hosted on Vercel Blob (public CDN).
 */
export const ANIMAL_VIDEOS: Record<string, string> = {
  "Alpaca": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/alpaca.mp4?v=3",
  "Bear": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/bear.mp4?v=3",
  "Cat": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/cat.mp4?v=3",
  "Dog": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/dog.mp4?v=3",
  "Elephant": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/elephant.mp4?v=3",
  "Fish": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/fish.mp4?v=3",
  "Gorilla": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/gorilla.mp4?v=3",
  "Handsome Xaven": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/handsome-xaven.mp4?v=3",
  "Hippo": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/hippo.mp4?v=3",
  "Ice Cream": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/ice-cream.mp4?v=3",
  "Jellyfish": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/jellyfish.mp4?v=3",
  "Kangaroo": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/kangaroo.mp4?v=3",
  "Lion": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/lion.mp4?v=3",
  "Mommy": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/mommy.mp4?v=3",
  "Nest": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/nest.mp4?v=3",
  "Octopus": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/octopus.mp4?v=3",
  "Panda": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/panda.mp4?v=3",
  "Quokka": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/quokka.mp4?v=3",
  "Renee": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/renee.mp4?v=3",
  "Shark": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/shark.mp4?v=3",
  "Turtle": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/turtle.mp4?v=3",
  "Unicorn": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/unicorn.mp4?v=3",
  "Vulture": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/vulture.mp4?v=3",
  "Whale": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/whale.mp4?v=3",
  "Yak": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/yak.mp4?v=3",
  "Zebra": "https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/zebra.mp4?v=3",
};
