/**
 * AUTO-GENERATED by scripts/generate-videos.ts. Do not edit by hand —
 * rerun the generator to refresh. Maps a lesson word to its Veo 3.1
 * clip under /public/assets/videos/.
 */
export const ANIMAL_VIDEOS: Record<string, string> = {
  "Alpaca": "/assets/videos/alpaca.mp4",
  "Bear": "/assets/videos/bear.mp4",
  "Cat": "/assets/videos/cat.mp4",
  "Dog": "/assets/videos/dog.mp4",
  "Elephant": "/assets/videos/elephant.mp4",
  "Fish": "/assets/videos/fish.mp4",
  "Gorilla": "/assets/videos/gorilla.mp4",
  "Hippo": "/assets/videos/hippo.mp4",
  "Ice Cream": "/assets/videos/ice-cream.mp4",
  "Lion": "/assets/videos/lion.mp4",
  "Whale": "/assets/videos/whale.mp4",
};
