/** AUTO-GENERATED by scripts/generate-music.ts. */
export interface DanceSong {
  id: string;
  title: string;
  emoji: string;
  src: string;
  durationSec: number;
  lyrics: string;
}

export const DANCE_SONGS: DanceSong[] = [
  {
    id: "abc-dance",
    title: "ABC Dance",
    emoji: "🔤",
    src: "/music/abc-dance.mp3",
    durationSec: 88.79,
    lyrics: `[[A0]]
[[B1]]
[10.2:] A B C D E F G
[13.9:] H I J K L M N O P
[22.0:] Q R S T U V
[25.8:] W X Y and Z
[[C2]]
[30.1:] Now I know my A B C's, dance with me, my ocean buddies!
[41.4:] Clap your hands and stomp your feet, wiggle wiggle to the beat!
[[B3]]
[50.0:] A B C D E F G
[53.8:] H I J K L M N O P
[61.9:] Q R S T U V
[65.7:] W X Y and Z
[[C4]]
[70.0:] Now I know my A B C's, dance with me, my ocean buddies!
[79.5:] Clap your hands and stomp your feet, wiggle wiggle to the beat!
[[D5]]
[86.2:] Yay!`,
  },
  {
    id: "animal-dance",
    title: "Animal Dance",
    emoji: "🦁",
    src: "/music/animal-dance.mp3",
    durationSec: 76.8,
    lyrics: `[[A0]]
[[B1]]
[10.1:] Hop like a bunny, hop hop hop!
[14.0:] Stomp like an elephant, stomp stomp stomp!
[18.0:] Wiggle like an octopus, wiggle wiggle wiggle!
[22.1:] Clap like a seal, clap clap clap!
[[C2]]
[26.0:] Animal dance, animal dance
[30.2:] Everybody do the animal dance!
[34.0:] Hop and stomp and wiggle and clap
[38.2:] Animal dance, animal dance!
[[B3]]
[42.1:] Jump like a deer, jump jump jump!
[46.0:] Flap like a crow, flap flap flap!
[50.0:] Splash like a dolphin, splash splash splash!
[54.0:] Roar like a lion, roar roar roar!
[[C4]]
[58.0:] Animal dance, animal dance
[62.2:] Everybody do the animal dance!
[66.0:] Hop and stomp and wiggle and clap
[70.1:] Animal dance, animal dance!
[[D5]]
[72.5:] Animal dance, hooray!`,
  },
  {
    id: "counting-dance",
    title: "Counting Dance",
    emoji: "🔟",
    src: "/music/counting-dance.mp3",
    durationSec: 76.51,
    lyrics: `[[A0]]
[5.6:] Count it in! One two three four!
[[B1]]
[9.5:] One two three, clap with me!
[13.1:] Four five six, stomp your feet!
[17.0:] Seven eight nine, jump up high!
[20.7:] Ten ten ten, wiggle again!
[[C2]]
[24.9:] Count and dance, count and dance
[28.8:] One two three four five!
[32.5:] Count and dance, count and dance
[36.3:] Six seven eight nine ten!
[[B3]]
[40.2:] One two three, clap with me!
[43.8:] Four five six, stomp your feet!
[47.7:] Seven eight nine, jump up high!
[51.4:] Ten ten ten, wiggle again!
[[C4]]
[55.6:] Count and dance, count and dance
[59.5:] One two three four five!
[63.2:] Count and dance, count and dance
[67.0:] Six seven eight nine ten!
[[D5]]
[71.1:] One to ten, hooray!`,
  },
  {
    id: "color-dance",
    title: "Color Dance",
    emoji: "🌈",
    src: "/music/color-dance.mp3",
    durationSec: 86.13,
    lyrics: `[[A0]]
[[B1]]
[8.1:] Red red red, clap clap clap!
[12.7:] Yellow yellow yellow, jump jump jump!
[16.3:] Green green green, wiggle wiggle wiggle!
[20.6:] Blue blue blue, stomp stomp stomp!
[[C2]]
[25.0:] Color dance, color dance
[28.8:] Red and yellow, green and blue!
[33.2:] Color dance, color dance
[37.0:] Rainbow colors, me and you!
[[D3]]
[42.0:] Orange orange orange, clap clap clap!
[45.9:] Purple purple purple, jump jump jump!
[49.9:] Pink pink pink, wiggle wiggle wiggle!
[54.0:] White white white, stomp stomp stomp!
[[C4]]
[58.3:] Color dance, color dance
[62.0:] Red and yellow, green and blue!
[66.4:] Color dance, color dance
[70.2:] Rainbow colors, me and you!
[[E5]]
[79.4:] Rainbow hooray!`,
  },
];

export const DANCE_SONG = DANCE_SONGS[0];
