/** AUTO-GENERATED by scripts/generate-music.ts. */
export interface DanceSong {
  id: string;
  title: string;
  emoji: string;
  src: string;
  durationSec: number;
  lyrics: string;
}

export const DANCE_SONGS: DanceSong[] = [
  {
    id: "abc-dance",
    title: "ABC Dance",
    emoji: "🔤",
    src: "/music/abc-dance.mp3",
    durationSec: 88.79,
    lyrics: `[[A0]]
[[B1]]
[10.2:] A B C D E F G
[13.9:] H I J K L M N O P
[22.0:] Q R S T U V
[25.8:] W X Y and Z
[[C2]]
[30.1:] Now I know my A B C's, dance with me, my ocean buddies!
[41.4:] Clap your hands and stomp your feet, wiggle wiggle to the beat!
[[B3]]
[50.0:] A B C D E F G
[53.8:] H I J K L M N O P
[61.9:] Q R S T U V
[65.7:] W X Y and Z
[[C4]]
[70.0:] Now I know my A B C's, dance with me, my ocean buddies!
[79.5:] Clap your hands and stomp your feet, wiggle wiggle to the beat!
[[D5]]
[86.2:] Yay!`,
  },
  {
    id: "animal-dance",
    title: "Animal Dance",
    emoji: "🦁",
    src: "/music/animal-dance.mp3",
    durationSec: 81.03,
    lyrics: `[[A0]]
[3.5:] (Baa baa! Moo!)
[5.8:] Let's dance, little friends!
[8.3:] (Cluck cluck!)
[[B1]]
[10.2:] Hop like a bunny, one two three
[13.9:] Stomp like an elephant, dance with me
[17.9:] Wiggle like an octopus under the sea
[21.9:] Clap like a seal, so happily
[[C2]]
[26.0:] Animal friends, come dance around
[30.0:] Jump up high, then touch the ground
[34.0:] Clap clap clap and stomp your feet
[38.0:] Wiggle together to the beat
[[B3]]
[42.0:] Leap like a deer through the forest green
[46.0:] Flap like a crow, what a dancing team
[50.0:] Swim like a dolphin, splash splash splash
[54.0:] Roar like a lion, then freeze like that
[[C4]]
[58.1:] Animal friends, come dance around
[62.1:] Jump up high, then touch the ground
[66.1:] Clap clap clap and stomp your feet
[70.1:] Wiggle together to the beat
[[D5]]
[73.9:] Hooray for our animal dance!`,
  },
  {
    id: "counting-dance",
    title: "Counting Dance",
    emoji: "🔟",
    src: "/music/counting-dance.mp3",
    durationSec: 73.87,
    lyrics: `[[A0]]
[[B1]]
[10.2:] One two three, clap with me
[13.9:] Four five six, do a wiggle twist
[16.4:] Seven eight, jump up straight
[18.2:] Nine and ten, let's count again
[[C2]]
[22.0:] Count and dance, count and play
[25.8:] Stomp your feet along the way
[30.1:] Clap your hands, jump up high
[32.1:] Wiggle low and touch the sky
[[B3]]
[34.2:] One two three four five
[38.0:] Six seven eight nine ten
[42.2:] Ten bright bubbles floating by
[45.9:] Pop pop pop and count again
[[C4]]
[50.0:] Count and dance, count and play
[53.8:] Stomp your feet along the way
[58.0:] Clap your hands, jump up high
[61.9:] Wiggle low and touch the sky
[[D5]]
[66.0:] One to ten, hooray!`,
  },
  {
    id: "color-dance",
    title: "Color Dance",
    emoji: "🌈",
    src: "/music/color-dance.mp3",
    durationSec: 77.43,
    lyrics: `[[A0]]
[[B1]]
[9.9:] Red red red, clap overhead
[13.8:] Orange and yellow, jump up and say hello
[17.9:] Green green green, wiggle like seaweed
[21.9:] Blue blue blue, stomp your little shoes
[[C2]]
[25.9:] Rainbow colors dance around
[29.9:] Clap your hands to every sound
[33.9:] Jump up high and wiggle low
[37.9:] Stomp your feet, go go go
[[B3]]
[41.9:] Purple like an octopus dancing in the sea
[45.9:] Pink like coral, sway with me
[50.0:] White like bubbles, floating up so light
[54.1:] All our colors shining bright
[[C4]]
[57.9:] Rainbow colors dance around
[62.0:] Clap your hands to every sound
[66.0:] Jump up high and wiggle low
[70.0:] Stomp your feet, go go go
[[D5]]
[73.0:] Rainbow hooray!`,
  },
];

export const DANCE_SONG = DANCE_SONGS[0];
