/**
 * Uploads every clip in public/assets/videos/*.mp4 to Vercel Blob
 * (public access, stable path videos/{slug}.mp4) and rewrites
 * src/lib/animal-videos.ts to point at the Blob CDN URLs.
 *
 * After this, the MP4s no longer need to live in git. Run:
 *   npx tsx scripts/upload-videos-blob.ts
 * Requires BLOB_READ_WRITE_TOKEN (read from .env.local).
 */
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { put } from "@vercel/blob";
import { getAlphabetEntriesWithVariants } from "../src/lib/alphabet-data.ts";
import { ANIMAL_INFO } from "../src/lib/animal-info.ts";

const VIDEO_DIR = path.join(process.cwd(), "public", "assets", "videos");
const MANIFEST = path.join(process.cwd(), "src", "lib", "animal-videos.ts");

async function loadDotEnvLocal() {
  if (process.env.BLOB_READ_WRITE_TOKEN) return;
  try {
    const raw = await readFile(path.join(process.cwd(), ".env.local"), "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i.exec(line);
      if (!m) continue;
      const [, k, v] = m;
      if (!process.env[k]) process.env[k] = v.replace(/^['"]|['"]$/g, "");
    }
  } catch {
    /* no .env.local */
  }
}

function fileSlug(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

// Blob paths are stable + cached `immutable` for a year, so overwriting
// a clip in place won't reach clients. Bump VIDEO_REV to append ?v=REV
// to the manifest URLs — that changes the CDN/browser cache key and
// forces the new bytes to load. --manifest-only re-emits the manifest
// (with the new rev) without re-uploading unchanged blobs.
const VIDEO_REV = process.env.VIDEO_REV || "1";
const MANIFEST_ONLY = process.argv.includes("--manifest-only");

async function main() {
  await loadDotEnvLocal();
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token && !MANIFEST_ONLY) {
    console.error("[blob] BLOB_READ_WRITE_TOKEN missing in .env.local. Aborting.");
    process.exit(1);
  }

  const files = (await readdir(VIDEO_DIR)).filter((f) => f.endsWith(".mp4")).sort();
  if (!files.length) {
    console.error("[blob] no mp4 files in public/assets/videos. Aborting.");
    process.exit(1);
  }

  // slug -> canonical lesson word
  const bySlug = new Map<string, string>();
  for (const entry of getAlphabetEntriesWithVariants()) {
    if (ANIMAL_INFO[entry.word]) bySlug.set(fileSlug(entry.word), entry.word);
  }

  const urlByWord = new Map<string, string>();
  for (const f of files) {
    const slug = f.replace(/\.mp4$/, "");
    const word = bySlug.get(slug);
    if (!word) {
      console.warn(`[blob] skip ${f} — no matching lesson word`);
      continue;
    }
    let url: string;
    if (MANIFEST_ONLY) {
      // Reuse the known stable path; just refresh the cache-bust rev.
      url = `https://zaygrhzrr99y8lju.public.blob.vercel-storage.com/videos/${f}`;
    } else {
      const data = await readFile(path.join(VIDEO_DIR, f));
      const blob = await put(`videos/${f}`, data, {
        access: "public",
        token: token as string,
        contentType: "video/mp4",
        // Stable, overwrite-on-rerun path so the manifest URL is durable.
        addRandomSuffix: false,
        allowOverwrite: true,
        cacheControlMaxAge: 31536000,
      });
      url = blob.url;
    }
    const versioned = `${url}?v=${VIDEO_REV}`;
    urlByWord.set(word, versioned);
    console.log(`[blob] ${MANIFEST_ONLY ? "linked" : "uploaded"} ${f} -> ${versioned}`);
  }

  const entries = [...urlByWord.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([word, url]) => `  ${JSON.stringify(word)}: ${JSON.stringify(url)},`);

  const body = `/**
 * AUTO-GENERATED by scripts/upload-videos-blob.ts. Do not edit by hand —
 * rerun the uploader to refresh. Maps a lesson word to its Veo 3.1 clip
 * hosted on Vercel Blob (public CDN).
 */
export const ANIMAL_VIDEOS: Record<string, string> = {
${entries.join("\n")}
};
`;
  await writeFile(MANIFEST, body);
  console.log(`\n[blob] manifest updated — ${entries.length} clips on Blob`);
}

main().catch((err) => {
  console.error("[blob] crashed:", err);
  process.exit(1);
});
